<div class="raw100" id="blog-main">
    <hr />  
    <h1>Blog - Module</h1>
        <p>With the power blog module installed on your system your able to post a variety of content to your website/application. With the blog module you're able to add content to your website on nearly any device. Simply select the blog option from the menu on the left of the screen. In the blog module, simply enter a title and dat for the blog. From there you will need to select a category and place some content in as an entry. With the content you can fill an entry with a book of text with some minimal formating, but you can also add images and video links.</p>
        
        <p>In order to add an image directly into the blog entry just press the blue Image Library button at the top of your screen. A panel will open to the right and let you upload an image. You may wish to put an image in a category but you don't have to (we still recommend doing so). After the image has uploaded. Select View Collections in the right panel. You should see your recently uploaded images promptly. Here you can click on an image to manage the details of the image. If you click the small red X you will be prompted to delete the image. Otherwise, you will be given a screen with a few options for the image you clicked. You can change the collection it is a part of or, if you'd like you can enter some decriptive terms in the Alt Text and Title Text fields. These will help your websites SEO. To place the image in the blog entry copy the Web Link. You can triple click to select the whole link. Back to the blog text field, you will see a small image icon in the top formating bar. Select this image and paste the Web Link into the space provided. This will put the image in your blog entry. You can then adjust its size by clicking the image and dragging, or you can select the image and set its position (in relation to how the text wraps around it), its Title, or add a link to a website.</p>

        <p>You can then select an image library below to connect a blog entry to a whole group of images. This field is of course optional. Click the Add Entry button and you will be notified via a status bar whether your entry was successfully saved or not.</p>

        <p>To view your entries, select the Blog Menu button and choose to View Entries. To edit an entry use the steps provided above. Archiving an entry just hides it from the public without you losing any information. Deleting it fully removes it from the database, with no option to undo the deletion.</p>
    <hr />
</div>